### ISSUE TITLE
Linux和Win的文件目录格式不同

### ISSUE THREAD

**Issue by hymoe** [qdd2104/helloPhp#1]
目前php打开文件使用
`fopen('..\data\user.csv','r')`
该写法只对Windows有效，Linux下应为
`fopen('../data/user.csv','r')`

- [ ] **需要寻找一种通用表示方式**

@skygoo

**Comment by skygoo** [comment]
`$file` = fopen('../data/user.csv','r');
直接改，windows可以打开
